### ISSUE TITLE
Deliverable 2 (linked to output 1). Scenario development

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/who3#17]
This stage will involve: (1) setting out high level policy scenarios of active transport uptake; (2) converting these changes into estimates of rates of shift towards walking and cycling down to route network levels; and (3) simulating the impacts of these scenarios on walking and cycling levels citywide. Scenario development will also be strongly informed by the transport scenarios assessed in Accra and Kathmandu as part of UHI project activities.

**Comment by Robinlovelace** [comment]
see #2

**Comment by Robinlovelace** [comment]
Quick question @mpadge, is there a quick way to load specific tables from data here into R?

https://github.com/ATFutures/whoIIreport/tree/master/docs

**Comment by mpadge** [comment]
sorry, massive delay right when you needed it, but ... not really, as far as i can figure out. But if it's really "specific" tables, then you could certainly find the start and end lines, and just use `readLines()`. That function is really cool - it's the basis of my [blog-creation repo](https://github.com/mpadge/mpadge.github.io/blob/source/src/pages/blog/make_entry.R#L8), aka, my re-coding of blogdown from scratch. Find your start and end points, readlines, then use `read.csv()`, like you use ... wherever that code was from other day.

**Comment by Robinlovelace** [comment]
Work in progress deliverable on this: https://github.com/ATFutures/who3/tree/master/scenarios

**Comment by mpadge** [comment]
### How to link scenarios to the detailed flow layers?

The [calibration](https://github.com/moveability/calibration) effectively scores the contribution of each mode of flow to total observed numbers, and so each flow layer can be presumed to represent some absolute (or relative) number of pedestrians. These layers are defined in terms of categories of start and end points (like transport, education, sustenance, and similar). For NYC, the overwhelmingly important layers are those start or ending with public transport, and that should hold similar for Accra - people who drive just don't walk as much. Secondary layers are things like public transport to parking, followed by other layers associated with actual activities.

A scenario will be manifest or measurable through overall changes in OD densities, and these reflect the aggregate contribution of all distinct layers. I could envision an approach something like this:

1. Correlate the observed *change* in OD values with a model of change in proportional contribution of the various layers (using significant layers only, of which there are generally only a handful). That will reveal the relative extent of change in those layers that would most closely reflect the aggregate OD change. (And none of that would require any re-calculation of layers, so model fitting would be instantaneous.)
2. Re-calculate the model representing the optimal combination of layers accordingly, and update the entire aggregate layer.
3. Use that updated layer as input to health-econ model to estimate health and economic effects of scenario.

That approach is then driven by the top-down approach of estimating gross changes in OD scores, and ends up with a highly detailed estimate of how such estimated changes would percolate down to health-economic impacts. Thoughts @Robinlovelace? Can you share any details of how you envision being able to estimate OD values? Are we going to use a case-study location other than Accra/Kathmandu?

**Comment by Robinlovelace** [comment]
For each of the scenarios, 

- 'Get walking', referring to a global (meaning without spatial input components, but with spatially distributed consequences) walking uptake, as a result of citywide policies to promote safe and attractive walking.

Good walking infrastructure and increased costs of driving could increase walking OD values and reduce driving OD values.

- 'Get cycling', referring to a global scenario of cycling, as a result of citywide policies to provide safe cycleways.

This would increase cycling OD values.

- 'Car diet', a global, citywide scenario of multi-modal transport change, showing reduced levels of driving following disincentives to own and use cars.

This would reduce car OD values

- 'Go public transport', a global scenario of public transport uptake, linked to [SDG 11](https://sustainabledevelopment.un.org/sdg11).

This would increase public transport, and potentially increase travel demand in areas well served by public transport.


- 'Car free', meaning investment in car free city centers and other spaces, other locally specific scenarios, such as reductions in car parking spaces.

This would reduce traffic into the city centre.

**Comment by Robinlovelace** [comment]
Documented here: just needs numbers on it: https://atfutures.github.io/upthat/articles/upthat.html

Heads-up @mpadge I suggest changing that vignette's name to scenarios and creating a new one. Good plan? Autodeploy took longer than 10 minutes, but think it was worth it!

**Comment by mpadge** [comment]
That's brilliant - and yes, agree that name would be better changed. Great work!

**Comment by Robinlovelace** [comment]
Documented here https://atfutures.github.io/upthat/articles/adaptation.html and the code is demonstrated here: https://github.com/ATFutures/who3/tree/master/scenarios

**Comment by mpadge** [comment]
The scenarios document is fabulous - you've done a grand job there!
