### ISSUE TITLE
Adaptation Manual

### ISSUE THREAD

**Issue by mpadge** [ATFutures/who3#5]
GanttStart: 2019-10-18
GanttDue: 2019-11-29

**Comment by Robinlovelace** [comment]
If we go with the shiny ui, this can be linked to https://shiny.rstudio.com/tutorial/written-tutorial/lesson2/

**Comment by Robinlovelace** [comment]
Heads-up @mpadge I'm going to implement GanttLab functionality in R for this. The easiest and most future proof way I think. All we need to do is add these lines somewhere in each issue:
```
GanttStart: 2016-09-26
GanttDue: 2016-10-25
```

**Comment by Robinlovelace** [comment]
See https://gitlab.com/ganttlab/ganttlab-live

**Comment by mpadge** [comment]
That's brilliant - nice discovery, and one i totally support. Looking forward to seeing it in action

**Comment by Robinlovelace** [comment]
Superseded by #14, output: https://atfutures.github.io/upthat/articles/adaptation.html
