### ISSUE TITLE
Add Gantt chart

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/who3#6]

**Comment by Robinlovelace** [comment]
One question for @mpadge (and @layik if interested): should [`gitgantt`](https://github.com/Robinlovelace/gitgantt) live in ATFutures? In other words: are you guys up for contributing/maintaining/submitting to CRAN? Could be a useful package for many people and has clear links to `calendar` (which is in some need of some tlc ; ).

**Comment by mpadge** [comment]
yeah sure, i say! I'll be happy to chip in, and to support maintenance, and yeah, let's put it in ATF because of alignment with calendar.

**Comment by Robinlovelace** [comment]
Sounds good. To reduce effort, will wait to hear back from ropensci peeps and then move. In the meantime, please 'do a Robin' and try to break it!
